version: '3.8'

services:
  bank_db:
    image: postgres:15
    environment:
      POSTGRES_DB: banco_db
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: JhairV2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ms-core-persona-cliente:
    build: ./ms-core-persona-cliente
    ports:
      - "8080:8080"
    depends_on:
      - bank_db
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181" # Puerto expuesto para acceso local
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - internal_bank_network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092" # Puerto expuesto para acceso local
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - internal_bank_network
  ms-core-fin-cuentas-movimientos:
    build: ./ms-core-fin-cuentas-movimientos
    ports:
      - "8080:8081"
    depends_on:
      - bank_db

volumes:
  postgres_data:

networks:
  internal_bank_network:
    driver: bridge
